//! Compares Rust output against the recorded MATSim 2026.0 reference for the shared PT fixtures.
//!
//! The reference is generated by `java_reference/run_reference.sh` into
//! `tests/resources/pt_reference/java/`. The comparison rules and the known deviations they encode
//! are documented in `docs/pt_java_reference.md`.
//!
//! Nothing here re-implements MATSim. Both sides are observed through the boundaries the rest of the
//! test suite uses: the controller writes the events, and the router the controller built answers
//! routing requests.

use macros::deterministic_id_test;
use matsim_rust::simulation::config::{CommandLineArgs, Config};
use matsim_rust::simulation::controller::controller::ControllerBuilder;
use matsim_rust::simulation::events::utils::read_events;
use matsim_rust::simulation::events::{
    ActivityEndEvent, ActivityStartEvent, EventTrait, EventsManager, PersonArrivalEvent,
    PersonDepartureEvent, PtTeleportationArrivalEvent, TeleportationArrivalEvent,
};
use matsim_rust::simulation::id::Id;
use matsim_rust::simulation::replanning::routing::{Facility, RoutingRequestBuilder, TripRouter};
use matsim_rust::simulation::scenario::network::Link;
use matsim_rust::simulation::scenario::population::InternalPerson;
use matsim_rust::simulation::scenario::{Coordinate, Scenario};
use matsim_rust::simulation::time::SimTime;
use serde_json::{Map, Value, json};
use std::cell::RefCell;
use std::path::Path;
use std::rc::Rc;

const FIXTURES: &str = "./tests/resources/pt_reference";
const JAVA_REFERENCE: &str = "./tests/resources/pt_reference/java";
const REFERENCE_COMMIT: &str = "c7a75ebeddc3ceb62959af046190064bf23770df";

/// The recorded reference carries this, and so must the Rust reader. Bump both when the normalized
/// shape changes.
const SCHEMA_VERSION: i64 = 2;

/// Runs the pt tutorial and compares the passenger's observable events against the reference.
///
/// The plan is supplied, so this fixture claims that Rust executes a supplied plan the way the
/// reference does. It says nothing about routing: the routing fixture covers that.
///
/// The comparison is per metric, because the two implementations do not agree on everything and the
/// point of the fixture is to say exactly what does and does not agree:
/// - events are matched by identity, so a different agent, mode, service or place is a different
///   journey and never a rounding difference;
/// - distances are compared exactly, at the precision both implementations compute;
/// - times are compared against an explicit one-step-per-leg bound rather than a loose tolerance,
///   because Rust hands an agent to the next engine one clock step after its leg ends.
///
/// This fixture executes the supplied plan with transit vehicles *not* driven, on both sides, so it
/// exercises activity/leg scheduling and teleport distances, not vehicle doors. A fixture that drives
/// vehicles is needed before boarding and alighting can be compared; the rules below say so rather
/// than claiming coverage they do not have.
#[deterministic_id_test(matsim_rust)]
fn supplied_plan_execution_matches_the_pinned_reference() {
    let config = Config::from_args(CommandLineArgs::new_with_path(
        "./tests/resources/pt_tutorial/pt_tutorial_config.yml",
    ));
    let output_dir = config.output().output_dir.clone();

    let reference = read_reference("supplied_plan");
    verify_same_conditions(&reference, &config);
    let clock_step = reference.clock_step();

    run(config);

    let reference = reference.events;
    let rust = normalize_events(&output_dir.join("events/events.0.binpb"));

    assert_eq!(
        reference.len(),
        rust.len(),
        "the reference and Rust recorded a different number of passenger events:\n{}",
        summarize(&reference, &rust),
    );

    // Both streams are in simulation order, so they line up event for event. Rust may be one clock
    // step behind per completed leg, which is the only difference allowed in the times.
    let mut worst_lag: f64 = 0.0;
    let mut completed_legs: f64 = 0.0;
    for (index, (expected, actual)) in reference.iter().zip(rust.iter()).enumerate() {
        for field in IDENTITY {
            assert_eq!(
                actual.get(*field),
                expected.get(*field),
                "event {index} differs in {field}:\n{}",
                summarize_pair(index, expected, actual),
            );
        }

        if expected["type"] == "arrival" {
            completed_legs += 1.0;
        }
        let lag = time_of(actual) - time_of(expected);
        assert!(
            lag >= 0.0,
            "event {index} is {}s earlier than the reference, which a delayed handoff cannot \
             explain:\n{}",
            -lag,
            summarize_pair(index, expected, actual),
        );
        let bound = completed_legs * clock_step;
        assert!(
            lag <= bound,
            "event {index} lags the reference by {lag:.0}s after {completed_legs:.0} legs, more than \
             the {bound:.0}s a delayed handoff explains:\n{}",
            summarize_pair(index, expected, actual),
        );
        worst_lag = worst_lag.max(lag);
    }

    // The lag is a real deviation, not a rule that grew to fit whatever the run produced: pin it, so
    // a change is a decision rather than a silent widening.
    assert_eq!(
        worst_lag,
        3.0 * clock_step,
        "the worst handoff lag changed; docs/pt_java_reference.md records the known deviation and \
         this bound, so update both rather than widening the rule"
    );
}

/// Fields that name an agent, a service, a mode or a place. These are compared exactly.
const IDENTITY: &[&str] = &[
    "type",
    "person",
    "actType",
    "legMode",
    "computationalRoutingMode",
    "link",
    "mode",
    "distance",
];

/// Checks that the recorded reference and the Rust config describe the same run.
///
/// The reference records the seed, the clock and a digest of every input. The digests are recorded
/// for provenance — they are what a reader hashes to detect an input that changed since recording —
/// and are not re-verified here, because that would need a hashing dependency in a test. What is
/// checked without one is the part a stale or mismatched fixture would actually get wrong: that every
/// recorded input still exists, and that both sides run the same seed over the same clock.
fn verify_same_conditions(reference: &Reference, config: &Config) {
    assert_eq!(
        reference.seed,
        config.computational_setup().random_seed as f64,
        "the reference ran with a different random seed than the Rust config; the two runs are not \
         comparable"
    );
    let qsim = config.qsim();
    assert_eq!(
        reference.clock_step(),
        1.0 / qsim.ticks_per_second as f64,
        "the reference's clock step does not follow from the Rust config's ticks_per_second"
    );
    for input in &reference.inputs {
        let path = Path::new(FIXTURES)
            .join(&reference.fixture)
            .join(&input.path);
        assert!(
            path.exists(),
            "the reference recorded {} as an input, but {} does not exist",
            input.role,
            path.display(),
        );
    }
}

/// The faster shared-stop transfer beats a direct service under the pinned Java default costs.
#[deterministic_id_test(matsim_rust)]
fn a_faster_shared_stop_transfer_beats_a_direct_service() {
    let request = load_request("routing_direct_vs_transfer");
    let config = Config::from_args(CommandLineArgs::new_with_path(
        "./tests/resources/pt_reference/routing_direct_vs_transfer/config.yml",
    ));
    let reference = read_reference("routing_direct_vs_transfer");
    verify_same_conditions(&reference, &config);
    let router = run(config);
    let rust = calc_pt_route(&request, &router);

    let expected = reference
        .itineraries
        .iter()
        .find(|itinerary| itinerary["id"] == request["id"])
        .expect("the request is recorded in the reference");

    assert_eq!(
        rides(&expected),
        vec![
            ride("a_to_b", "ra", "rb", 28800.0),
            ride("b_to_c", "rb", "rc", 29700.0),
        ],
        "the reference no longer takes the recorded transfer; this fixture needs a new request"
    );
    assert_eq!(
        arrival_time(expected),
        30300.0,
        "the reference's transfer arrival changed"
    );

    assert_eq!(
        rides(&rust),
        rides(&expected),
        "Rust's selected services differ from the pinned Java itinerary"
    );
    assert_eq!(
        arrival_time(&rust),
        arrival_time(&expected),
        "Rust's arrival differs from the pinned Java itinerary"
    );
    let rust_cost_seconds = arrival_time(&rust) - request["departure_time"].as_f64().unwrap()
        + 300.0 * rides(&rust).len().saturating_sub(1) as f64;
    let rust_cost_utils = rust_cost_seconds * 12.0 / 3600.0;
    assert_eq!(
        expected["generalized_cost"].as_f64(),
        Some(rust_cost_utils),
        "Rust's generalized cost differs from MATSim's selected-route cost"
    );
    assert_eq!(
        rust["legs"]
            .as_array()
            .unwrap()
            .iter()
            .map(|leg| leg["mode"].as_str().unwrap())
            .collect::<Vec<_>>(),
        expected["legs"]
            .as_array()
            .unwrap()
            .iter()
            .map(|leg| leg["mode"].as_str().unwrap())
            .collect::<Vec<_>>(),
        "Rust's access, transfer and egress legs differ from the pinned Java itinerary"
    );
}

/// Passenger mode mappings let competing transit route modes use their own scoring costs.
#[deterministic_id_test(matsim_rust)]
fn mapped_passenger_modes_match_the_pinned_java_itinerary() {
    let request = load_request("routing_mapped_modes");
    let config = Config::from_args(CommandLineArgs::new_with_path(
        "./tests/resources/pt_reference/routing_mapped_modes/config.yml",
    ));
    let reference = read_reference("routing_mapped_modes");
    verify_same_conditions(&reference, &config);
    let router = run(config);
    let rust = calc_pt_route(&request, &router);

    let expected = reference
        .itineraries
        .iter()
        .find(|itinerary| itinerary["id"] == request["id"])
        .expect("the request is recorded in the reference");

    assert_eq!(rides(expected), vec![ride("direct", "ra", "rc", 28800.0)]);
    assert_eq!(arrival_time(expected), 31800.0);
    assert_eq!(rides(&rust), rides(expected));
    assert_eq!(arrival_time(&rust), arrival_time(expected));
    assert_eq!(
        rust["legs"]
            .as_array()
            .unwrap()
            .iter()
            .map(|leg| leg["mode"].as_str().unwrap())
            .collect::<Vec<_>>(),
        vec!["walk", "rail", "walk"],
        "mapped train service should produce a rail passenger leg"
    );
}

/// A transfer between separate platforms retains the walk leg and its five-second safety margin.
#[deterministic_id_test(matsim_rust)]
fn a_distinct_platform_transfer_matches_the_pinned_reference() {
    let config = Config::from_args(CommandLineArgs::new_with_path(
        "./tests/resources/pt_reference/routing_distinct_platform_transfer/config.yml",
    ));
    let reference = read_reference("routing_distinct_platform_transfer");
    verify_same_conditions(&reference, &config);
    let router = run(config);
    for (index, expected_rides, end) in [
        (
            0,
            vec![
                ride("a_to_b", "ra", "rb", 28800.0),
                ride("b_to_c_bus", "rb_platform", "rc", 29556.0),
            ],
            29856.0,
        ),
        (
            1,
            vec![
                ride("a_to_b", "ra", "rb", 28801.0),
                ride("b_to_c_bus", "rb_platform", "rc", 29700.0),
            ],
            30000.0,
        ),
        (
            2,
            vec![
                ride("a_to_b", "ra", "rb", 31800.0),
                ride("b_to_c", "rb_platform", "rc", 32700.0),
            ],
            33300.0,
        ),
        (
            3,
            vec![ride("direct_unavailable", "ro", "rc_unavailable", 28800.0)],
            36000.0,
        ),
    ] {
        let request = load_request_at("routing_distinct_platform_transfer", index);
        let rust = calc_pt_route(&request, &router);
        let expected = reference
            .itineraries
            .iter()
            .find(|itinerary| itinerary["id"] == request["id"])
            .expect("the request is recorded in the reference");
        assert_eq!(rides(&rust), expected_rides);
        assert_eq!(rides(&rust), rides(expected));
        assert_eq!(arrival_time(&rust), end);
        assert_eq!(arrival_time(&rust), arrival_time(expected));
        assert_eq!(
            rust["legs"]
                .as_array()
                .unwrap()
                .iter()
                .map(|leg| leg["mode"].as_str().unwrap())
                .collect::<Vec<_>>(),
            expected["legs"]
                .as_array()
                .unwrap()
                .iter()
                .map(|leg| leg["mode"].as_str().unwrap())
                .collect::<Vec<_>>()
        );
        if index < 3 {
            assert!(rust["legs"].as_array().unwrap().iter().any(|leg| {
                leg["mode"] == "walk"
                    && leg["arrival_time"].as_f64().unwrap()
                        - leg["departure_time"].as_f64().unwrap()
                        == 151.0
                    && leg["distance"] == 130.0
            }));
        }
    }
}

/// A plan routed through separate platforms completes its walk and transit legs in QSim.
#[deterministic_id_test(matsim_rust)]
fn a_distinct_platform_transfer_executes_through_the_simulation_runner() {
    let config = Config::from_args(CommandLineArgs::new_with_path(
        "./tests/resources/pt_reference/routing_distinct_platform_transfer/execution.yml",
    ));
    let output_dir = config.output().output_dir.clone();
    run(config);

    let events = normalize_events(&output_dir.join("events/events.0.binpb"));
    let passenger_events: Vec<_> = events
        .iter()
        .filter(|event| event["person"] == "transfer-person")
        .collect();
    let departures: Vec<_> = passenger_events
        .iter()
        .filter(|event| event["type"] == PersonDepartureEvent::TYPE)
        .map(|event| {
            (
                event["legMode"].as_str().unwrap().to_string(),
                event["link"].as_str().unwrap().to_string(),
            )
        })
        .collect();
    assert_eq!(
        departures,
        [
            ("walk".into(), "11".into()),
            ("pt".into(), "11".into()),
            ("walk".into(), "12".into()),
            ("pt".into(), "23".into()),
            ("walk".into(), "33".into()),
        ]
    );
    let arrivals = passenger_events
        .iter()
        .filter(|event| event["type"] == PersonArrivalEvent::TYPE)
        .count();
    assert_eq!(arrivals, departures.len());
    assert!(
        passenger_events
            .iter()
            .any(|event| { event["type"] == ActivityStartEvent::TYPE && event["actType"] == "w" })
    );
}

/// Runs one simulation and returns the router its controller built, so both boundaries the fixtures
/// compare are the ones the simulation itself uses.
///
/// This mirrors how the rest of the suite drives a run; keeping it here means a change to the
/// controller or the scenario loader shows up in the fixtures rather than hiding behind a
/// fixture-specific setup.
fn run(config: Config) -> TripRouter {
    let scenario = Scenario::load(config);
    let controller = ControllerBuilder::default_with_scenario(scenario)
        .build()
        .unwrap();
    let (router, _population) = controller.run();
    router
}

fn load_request(fixture: &str) -> Value {
    load_request_at(fixture, 0)
}

fn load_request_at(fixture: &str, index: usize) -> Value {
    let path = Path::new("./tests/resources/pt_reference")
        .join(fixture)
        .join("requests.json");
    let content: Value = serde_json::from_str(&std::fs::read_to_string(&path).unwrap())
        .unwrap_or_else(|e| panic!("cannot read the recorded request at {path:?}: {e}"));
    content["requests"][index].clone()
}

fn read_reference(fixture: &str) -> Reference {
    let path = Path::new(JAVA_REFERENCE).join(format!("{fixture}.json"));
    let content: Value = serde_json::from_str(&std::fs::read_to_string(&path).unwrap())
        .unwrap_or_else(|e| panic!("cannot read the recorded reference at {path:?}: {e}"));
    assert_eq!(
        content["schema_version"].as_i64(),
        Some(SCHEMA_VERSION),
        "the recorded reference at {path:?} has a different schema version; rerun \
         java_reference/run_reference.sh"
    );
    assert_eq!(
        content["reference"]["commit"].as_str(),
        Some(REFERENCE_COMMIT),
        "the recorded reference at {path:?} is not MATSim 2026.0"
    );
    Reference {
        fixture: fixture.to_string(),
        seed: content["reference"]["seed"]
            .as_f64()
            .expect("a seed is recorded"),
        time_step_size: content["reference"]["time_step_size"]
            .as_f64()
            .expect("a time step size is recorded"),
        inputs: content["reference"]["inputs"]
            .as_array()
            .expect("the inputs are recorded")
            .iter()
            .map(|input| Input {
                role: input["role"]
                    .as_str()
                    .expect("an input has a role")
                    .to_string(),
                path: input["path"]
                    .as_str()
                    .expect("an input has a path")
                    .to_string(),
            })
            .collect(),
        itineraries: content["itineraries"].as_array().unwrap().clone(),
        events: content["events"].as_array().unwrap().clone(),
    }
}

struct Reference {
    /// Fixture directory the recorded input paths are relative to.
    fixture: String,
    seed: f64,
    time_step_size: f64,
    inputs: Vec<Input>,
    itineraries: Vec<Value>,
    events: Vec<Value>,
}

struct Input {
    role: String,
    /// Relative to the fixture directory, as the harness records it.
    path: String,
}

impl Reference {
    /// The simulation clock step in seconds, from the recorded time-step size.
    ///
    /// Read from the reference rather than hardcoded, so the comparison rule follows the recorded
    /// clock instead of assuming one.
    fn clock_step(&self) -> f64 {
        self.time_step_size
    }
}

/// Reads the events Rust wrote and reduces them to the shape the harness records.
///
/// Only the passenger-relevant types are kept, so a vehicle event or an extra field cannot make the
/// comparison pass or fail for the wrong reason.
fn normalize_events(path: &Path) -> Vec<Value> {
    let events = Rc::new(RefCell::new(Vec::new()));
    let sink = Rc::clone(&events);
    let mut manager = EventsManager::new();
    manager.on_any(move |event: &dyn EventTrait| {
        if let Some(record) = normalize_event(event) {
            sink.borrow_mut().push(record);
        }
    });
    read_events(&mut manager, path).unwrap();

    // File order is kept, as on the reference side: the order the simulation emitted the events in
    // is the order the journey happened in.
    events.borrow().clone()
}

/// Reads a `start`/`end` activity event. Both carry the same fields and differ only in their type
/// name, so the shape is written once.
fn activity_record(
    record: &mut Map<String, Value>,
    time: SimTime,
    type_name: &str,
    person: &Id<InternalPerson>,
    act_type: &Id<String>,
    link: &Id<Link>,
    coordinate: &Coordinate,
) {
    record.insert("time".into(), json!(millis(seconds(time))));
    record.insert("type".into(), json!(type_name));
    record.insert("person".into(), json!(person.external()));
    record.insert("actType".into(), json!(act_type.external()));
    record.insert("link".into(), json!(link.external()));
    record.insert("x".into(), json!(coordinate.x));
    record.insert("y".into(), json!(coordinate.y));
}

fn normalize_event(event: &dyn EventTrait) -> Option<Value> {
    let any = event.as_any();
    let mut record = Map::new();

    if let Some(event) = any.downcast_ref::<ActivityStartEvent>() {
        activity_record(
            &mut record,
            event.time,
            ActivityStartEvent::TYPE,
            &event.person,
            &event.act_type,
            &event.link,
            &event.coordinate,
        );
    } else if let Some(event) = any.downcast_ref::<ActivityEndEvent>() {
        activity_record(
            &mut record,
            event.time,
            ActivityEndEvent::TYPE,
            &event.person,
            &event.act_type,
            &event.link,
            &event.coordinate,
        );
    } else if let Some(event) = any.downcast_ref::<PersonDepartureEvent>() {
        record.insert("time".into(), json!(millis(seconds(event.time))));
        record.insert("type".into(), json!(PersonDepartureEvent::TYPE));
        record.insert("person".into(), json!(event.person.external()));
        record.insert("legMode".into(), json!(event.leg_mode.external()));
        record.insert(
            "computationalRoutingMode".into(),
            json!(routing_mode(event)),
        );
        record.insert("link".into(), json!(event.link.external()));
    } else if let Some(event) = any.downcast_ref::<PersonArrivalEvent>() {
        record.insert("time".into(), json!(millis(seconds(event.time))));
        record.insert("type".into(), json!(PersonArrivalEvent::TYPE));
        record.insert("person".into(), json!(event.person.external()));
        record.insert("legMode".into(), json!(event.leg_mode.external()));
        record.insert("link".into(), json!(event.link.external()));
    } else if let Some(event) = any.downcast_ref::<PtTeleportationArrivalEvent>() {
        // The reference reports a teleported pt leg as a plain `travelled` with mode `pt`; the extra
        // service fields are Rust's own and are compared by the routing fixture instead.
        record.insert("time".into(), json!(millis(seconds(event.time))));
        record.insert("type".into(), json!("travelled"));
        record.insert("person".into(), json!(event.person.external()));
        record.insert("mode".into(), json!(event.mode.external()));
        record.insert("distance".into(), json!(event.distance));
    } else if let Some(event) = any.downcast_ref::<TeleportationArrivalEvent>() {
        record.insert("time".into(), json!(millis(seconds(event.time))));
        record.insert("type".into(), json!(TeleportationArrivalEvent::TYPE));
        record.insert("person".into(), json!(event.person.external()));
        record.insert("mode".into(), json!(event.mode.external()));
        record.insert("distance".into(), json!(event.distance));
    } else {
        return None;
    }
    Some(Value::Object(record))
}

/// The leg's computational routing mode. `pt` is the only value this port records, so it is also
/// the fallback; the attribute is optional because a non-pt leg does not carry one.
fn routing_mode(event: &PersonDepartureEvent) -> Value {
    match event.attributes.get::<String>("computational_routing_mode") {
        Some(mode) => json!(mode),
        None => json!("pt"),
    }
}

fn time_of(record: &Value) -> f64 {
    record["time"]
        .as_f64()
        .expect("a normalized event has a time")
}

fn seconds(time: SimTime) -> f64 {
    time.as_duration().as_secs_f64()
}

/// Millisecond resolution, matching the harness: finer than either clock, so it cannot hide a
/// difference in how the two implementations round.
fn millis(value: f64) -> f64 {
    (value * 1_000.0).round() / 1_000.0
}

fn calc_pt_route(request: &Value, router: &TripRouter) -> Value {
    let facility = |end: &str| {
        let end = &request[end];
        Facility::new_link_wrapper(
            Coordinate::new_2d(end["x"].as_f64().unwrap(), end["y"].as_f64().unwrap()),
            Id::<Link>::create(end["link"].as_str().unwrap()),
        )
    };
    let from = facility("from");
    let to = facility("to");
    let elements = router
        .calc_route(
            &Id::create(request["mode"].as_str().unwrap()),
            RoutingRequestBuilder::default()
                .from(&from)
                .to(&to)
                .departure_time(SimTime::from_secs(
                    request["departure_time"].as_f64().unwrap() as u64,
                ))
                .build()
                .unwrap(),
        )
        .expect("the recorded request has a path on both sides");

    let mut arrival = request["departure_time"].as_f64().unwrap();
    let mut legs = Vec::new();
    for element in elements {
        let Some(leg) = element.as_leg() else {
            continue;
        };
        let departure = leg
            .dep_time
            .map(|time| millis(seconds(time)))
            .unwrap_or(arrival);
        let travel_time = leg.trav_time.map(|time| time.as_secs_f64()).unwrap_or(0.0);
        let mut rides = Vec::new();
        if let Some(pt) = leg.route.as_ref().and_then(|route| route.as_pt()) {
            let description = &pt.description;
            rides.push(json!({
                "line": description.transit_line_id,
                "route": description.transit_route_id,
                "access_stop": description.access_facility_id,
                "egress_stop": description.egress_facility_id,
                "boarding_time": description.boarding_time.map(|time| millis(seconds(time))),
            }));
        }
        legs.push(json!({
            "mode": leg.mode.external(),
            "departure_time": departure,
            "arrival_time": millis(departure + travel_time),
            "distance": leg.route.as_ref().and_then(|route| route.as_generic().distance()),
            "rides": rides,
        }));
        arrival = departure + travel_time;
    }
    json!({ "result": "found", "arrival_time": millis(arrival), "legs": legs })
}

fn ride(route: &str, board: &str, alight: &str, boarding_time: f64) -> Value {
    json!({
        "line": "Reference Line",
        "route": route,
        "access_stop": board,
        "egress_stop": alight,
        "boarding_time": boarding_time,
    })
}

/// The rides of an itinerary, in the order they are travelled, reduced to the service identity the
/// comparison is about. Both implementations record a ride under the same keys, so a missing field
/// reads as null and fails the comparison instead of being silently accepted.
fn rides(itinerary: &Value) -> Vec<Value> {
    itinerary["legs"]
        .as_array()
        .expect("an itinerary has legs")
        .iter()
        .flat_map(|leg| leg["rides"].as_array().cloned().unwrap_or_default())
        .map(|ride| {
            json!({
                "line": ride["line"],
                "route": ride["route"],
                "access_stop": ride["access_stop"],
                "egress_stop": ride["egress_stop"],
                "boarding_time": ride["boarding_time"],
            })
        })
        .collect()
}

fn arrival_time(itinerary: &Value) -> f64 {
    itinerary["arrival_time"]
        .as_f64()
        .unwrap_or_else(|| panic!("{itinerary} has no arrival time"))
}

/// One line describing an event. It walks `IDENTITY` rather than repeating the field list, so a
/// field added to the comparison also shows up in the failure message.
fn summarize_event(record: &Value) -> String {
    let identity: Vec<String> = IDENTITY
        .iter()
        .filter_map(|key| record.get(*key).map(|value| format!("{key}={value}")))
        .collect();
    format!("t={:.0} {}", time_of(record), identity.join(" "))
}

fn summarize_pair(index: usize, reference: &Value, rust: &Value) -> String {
    format!(
        "  event {index}\n    reference: {}\n    rust:      {}",
        summarize_event(reference),
        summarize_event(rust),
    )
}

fn summarize(reference: &[Value], rust: &[Value]) -> String {
    let longer = reference.len().max(rust.len());
    (0..longer)
        .map(|index| {
            summarize_pair(
                index,
                reference.get(index).unwrap_or(&Value::Null),
                rust.get(index).unwrap_or(&Value::Null),
            )
        })
        .collect::<Vec<_>>()
        .join("\n")
}
